const API_BASE='https://abnydnnafyosrakkgajy.supabase.co/functions/v1/v6-test1-api';
let manager=null,current=null,queue=[];
const $=id=>document.getElementById(id);
async function api(a,b={}){const r=await fetch(`${API_BASE}?a=${a}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const t=await r.text();let d={};try{d=JSON.parse(t)}catch{}if(!r.ok)throw Error(d.error||t||`HTTP ${r.status}`);return d}
function flash(text){$('mmsg').textContent=text;$('mmsg').scrollIntoView({behavior:'smooth',block:'center'})}
async function login(){try{const d=await api('login',{pin:$('pin').value.trim()});const u=Array.isArray(d)?d[0]:d;if(!u||!['manager','admin','lead_supervisor'].includes(u.access_level))throw Error('Use a management test PIN.');manager={...u,employee_id:u.employee_id||u.id};$('login').classList.add('hidden');$('mgr').classList.remove('hidden');$('who').textContent=`${u.name} — Test 3 Management`;await load()}catch(e){$('msg').textContent=e.message}}
async function load(){try{const d=await api('manager_queue',{manager_id:manager.employee_id});queue=Array.isArray(d)?d:[];const v=await api('verification_queue',{manager_id:manager.employee_id});$('queue').innerHTML=queue.length?queue.map(x=>`<div class="item ${x.corrective_status==='completed_pending_verification'?'pending':''}"><b>#${x.finding_no} ${x.equipment_code} — ${x.equipment_description}</b><br><span>${x.current_severity.toUpperCase()} · ${x.corrective_status||'OPEN'}</span><button class="open" data-id="${x.finding_id}">OPEN</button></div>`).join(''):'<p>No owned/open findings.</p>';$('verifyQueue').innerHTML=Array.isArray(v)&&v.length?v.map(x=>`<div class="item verify"><b>VERIFY #${x.finding_no} ${x.equipment_code}</b><p>${x.completion_comment}</p><small>Completed by ${x.completed_by_name}${x.evidence_file_name?` · Photo: ${x.evidence_file_name}`:''}</small><textarea id="vc-${x.corrective_action_id}" placeholder="Verification comment / rejection reason"></textarea><button class="approve" data-ca="${x.corrective_action_id}" data-no="${x.finding_no}">APPROVE & CLOSE</button><button class="reject danger" data-ca="${x.corrective_action_id}" data-no="${x.finding_no}">REJECT — REWORK REQUIRED</button></div>`).join(''):'<p>No items awaiting your independent verification.</p>';bind()}catch(e){$('mmsg').textContent=e.message}}
function bind(){document.querySelectorAll('.open').forEach(b=>b.onclick=()=>openFinding(b.dataset.id));document.querySelectorAll('.approve').forEach(b=>b.onclick=()=>verify(b.dataset.ca,'approved',b.dataset.no));document.querySelectorAll('.reject').forEach(b=>b.onclick=()=>verify(b.dataset.ca,'rejected',b.dataset.no))}
function openFinding(id){current=queue.find(x=>x.finding_id===id);if(!current)return;$('detail').classList.remove('hidden');$('detailText').innerHTML=`<b>Finding #${current.finding_no}</b><p>${current.equipment_code} — ${current.equipment_description}</p><p>${current.description}</p><p><b>Original/current severity:</b> ${current.current_severity}</p>${current.action_plan?`<div class="summary"><b>Action plan</b><p>${current.action_plan}</p></div>`:''}`;const owned=current.assigned_to===manager.employee_id&&['assigned','accepted'].includes(current.corrective_status);$('completeBtn').classList.toggle('hidden',!owned);$('completePanel').classList.add('hidden');$('mmsg').textContent='';$('detail').scrollIntoView({behavior:'smooth'})}
function showComplete(){$('completePanel').classList.remove('hidden');$('completion').value='';$('evidence').value='';$('second').checked=false;$('completePanel').scrollIntoView({behavior:'smooth'})}
async function complete(){const comment=$('completion').value.trim(),file=$('evidence').files[0];if(!comment){$('mmsg').textContent='Describe the work completed.';return}if(!file){$('mmsg').textContent='Select an after-work photo for this pilot.';return}try{const d=await api('complete_corrective',{manager_id:manager.employee_id,finding_id:current.finding_id,completion_comment:comment,equipment_status:$('equipStatus').value,file_name:file.name,request_second_verification:$('second').checked});const r=Array.isArray(d)?d[0]:d;const text=r.verification_required?'Work completed. AWAITING INDEPENDENT VERIFICATION.':'Work completed and finding CLOSED under the severity-based rule.';$('completePanel').classList.add('hidden');$('detail').classList.add('hidden');await load();flash(text);window.scrollTo({top:0,behavior:'smooth'})}catch(e){$('mmsg').textContent=e.message}}
async function verify(ca,decision,no){const comment=$(`vc-${ca}`).value.trim();if(decision==='rejected'&&!comment){flash('A rejection reason is required.');return}try{await api('verify_corrective',{manager_id:manager.employee_id,corrective_action_id:ca,decision,comment});$('detail').classList.add('hidden');current=null;await load();const text=decision==='approved'?`Finding #${no} verified and closed.`:`Finding #${no} rejected and returned to the responsible manager for rework.`;flash(text);window.scrollTo({top:0,behavior:'smooth'})}catch(e){flash(e.message)}}
$('loginBtn').onclick=login;$('refresh').onclick=load;$('completeBtn').onclick=showComplete;$('submitComplete').onclick=complete;$('back').onclick=()=>{$('detail').classList.add('hidden');load()};
