// Morning Update v2 enhancement: timestamped owner site snapshot + all-employee location check-in.
const _baseRefresh=refresh;
refresh=async function(){await _baseRefresh();if(!home)return;const pc=$('presenceCard');if(pc)pc.classList.toggle('hidden',!!home.permissions.management);};
const _baseRenderMorning=renderMorning;
renderMorning=function(d){_baseRenderMorning(d);const role=(d.employee?.role||'').toLowerCase();if(!role.includes('owner'))return;const sites=d.site_snapshot||[];const stamp=new Date().toLocaleString([], {month:'numeric',day:'numeric',hour:'numeric',minute:'2-digit'});const cards=['JK Farms','Borland'].map(name=>{const s=sites.find(x=>x.plant===name)||{};return `<div class="sitebox"><h3>${esc(name)}</h3><div class="sitepeople">${Number(s.people||0)}</div><div class="small">people checked in</div><div class="sitemetrics"><span><b>${Number(s.vehicle_inspections||0)}</b> Vehicle / Equipment</span><span><b>${Number(s.work_area_inspections||0)}</b> Work Area / Plant</span></div></div>`}).join('');$('morningContent').insertAdjacentHTML('afterbegin',`<div class="ownerSnapshot"><div class="snapshotHead"><h3>Plant Activity Snapshot</h3><span>Updated ${esc(stamp)}</span></div><div class="sitegrid">${cards}</div><p class="small">Counts reflect employees who checked in to each plant today. Inspection counts reflect today's recorded activity and update when Morning Update is refreshed.</p></div>`);};
async function saveEmployeeLocation(){const loc=$('employeeLocation').value;if(!loc)return alert('Select where you are working today.');const b=$('saveEmployeeLocation');b.disabled=true;b.textContent='SAVING...';try{await api('morning_checkin',{employee_id:user.employee_id,location:loc,note:$('employeeLocationNote').value.trim()});$('employeeLocationStatus').textContent='Location saved — '+new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});}catch(e){$('employeeLocationStatus').textContent=e.message}finally{b.disabled=false;b.textContent='SAVE / UPDATE LOCATION'}}
$('saveEmployeeLocation').onclick=saveEmployeeLocation;
async function endEmployeeDay(){if(!confirm('End your workday and check out? You can check back in later if needed.'))return;const b=$('endEmployeeDay');b.disabled=true;b.textContent='CHECKING OUT...';try{await api('morning_checkout',{employee_id:user.employee_id});$('employeeLocationStatus').textContent='Checked out — '+new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});await refresh();}catch(e){$('employeeLocationStatus').textContent=e.message}finally{b.disabled=false;b.textContent='END DAY / CHECK OUT'}}
async function endManagerDay(){if(!confirm('End your workday and check out? You can check back in later if needed.'))return;const b=$('endManagerDay');b.disabled=true;b.textContent='CHECKING OUT...';try{await api('morning_checkout',{employee_id:user.employee_id});await loadMorning();}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent='END DAY / CHECK OUT'}}
$('endEmployeeDay').onclick=endEmployeeDay;$('endManagerDay').onclick=endManagerDay;
